# Generated by Django 5.2.1 on 2025-06-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'vlog'},
        ),
    ]
